[workspace]
members = [
    "backend/canisters/settlement/api",
    "backend/canisters/settlement/impl",
    "backend/integration_tests",
]
resolver = "2"

[workspace.dependencies]
candid = "0.10"
hex = "0.4"
ic-cdk = "0.17"
ic-cdk-timers = "0.11"
ic-stable-structures = "0.6"
pocket-ic = "9"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"

[profile.release]
lto = true
opt-level = "z"
